// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StrikeShield.Infrastructure.Persistence;

#nullable disable

namespace StrikeShield.Infrastructure.Migrations
{
    [DbContext(typeof(StrikeShieldDbContext))]
    [Migration("20260714090000_AddPlaybooksAndOrchestration")]
    partial class AddPlaybooksAndOrchestration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("StrikeShield.Domain.Entities.AppUser", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("character varying(320)");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<int>("Role").HasColumnType("integer");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("OrganizationId");

                b.ToTable("Users");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Artifact", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("Content").IsRequired().HasColumnType("text");
                b.Property<string>("ContentType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("FileName").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<Guid>("StepRunId").HasColumnType("uuid");

                b.HasKey("Id");
                b.HasIndex("StepRunId");

                b.ToTable("Artifacts");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Client", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");

                b.HasKey("Id");
                b.HasIndex("OrganizationId");

                b.ToTable("Clients");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Engagement", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string[]>("AllowedScopeRules").IsRequired().HasColumnType("text[]");
                b.Property<DateTimeOffset?>("ApprovedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("ApprovedBy").HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("AuthorizationEvidenceUri").HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<Guid>("ProjectId").HasColumnType("uuid");
                b.Property<string>("RulesOfEngagement").HasMaxLength(4000).HasColumnType("character varying(4000)");
                b.Property<DateTimeOffset>("ScopeEnd").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset>("ScopeStart").HasColumnType("timestamp with time zone");

                b.HasKey("Id");
                b.HasIndex("ProjectId");

                b.ToTable("Engagements");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Organization", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");

                b.HasKey("Id");

                b.ToTable("Organizations");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Playbook", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");

                b.HasKey("Id");
                b.HasIndex("Slug").IsUnique();

                b.ToTable("Playbooks");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.PlaybookStep", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("ArgsTemplate").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("ImageRepository").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<string>("ImageTag").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<long>("MemoryLimitBytes").HasColumnType("bigint");
                b.Property<long>("NanoCpus").HasColumnType("bigint");
                b.Property<int>("Order").HasColumnType("integer");
                b.Property<Guid>("PlaybookId").HasColumnType("uuid");
                b.Property<int>("TimeoutSeconds").HasColumnType("integer");
                b.Property<string>("ToolName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");

                b.HasKey("Id");
                b.HasIndex("PlaybookId");

                b.ToTable("PlaybookSteps");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Project", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<Guid>("ClientId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");

                b.HasKey("Id");
                b.HasIndex("ClientId");

                b.ToTable("Projects");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.ScanJob", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("EngagementId").HasColumnType("uuid");
                b.Property<Guid>("PlaybookId").HasColumnType("uuid");
                b.Property<int>("Status").HasColumnType("integer");
                b.Property<Guid>("TargetId").HasColumnType("uuid");

                b.HasKey("Id");
                b.HasIndex("EngagementId");
                b.HasIndex("PlaybookId");
                b.HasIndex("TargetId");

                b.ToTable("ScanJobs");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.StepRun", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("ContainerId").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("ErrorMessage").HasMaxLength(4000).HasColumnType("character varying(4000)");
                b.Property<long?>("ExitCode").HasColumnType("bigint");
                b.Property<Guid>("PlaybookStepId").HasColumnType("uuid");
                b.Property<Guid>("ScanJobId").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("StartedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("Status").HasColumnType("integer");

                b.HasKey("Id");
                b.HasIndex("PlaybookStepId");
                b.HasIndex("ScanJobId");

                b.ToTable("StepRuns");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Target", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("ProjectId").HasColumnType("uuid");
                b.Property<int>("Type").HasColumnType("integer");
                b.Property<string>("Value").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");

                b.HasKey("Id");
                b.HasIndex("ProjectId");

                b.ToTable("Targets");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Artifact", b =>
            {
                b.HasOne("StrikeShield.Domain.Entities.StepRun", "StepRun")
                    .WithMany("Artifacts")
                    .HasForeignKey("StepRunId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("StepRun");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.AppUser", b =>
            {
                b.HasOne("StrikeShield.Domain.Entities.Organization", "Organization")
                    .WithMany("Users")
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Organization");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Client", b =>
            {
                b.HasOne("StrikeShield.Domain.Entities.Organization", "Organization")
                    .WithMany("Clients")
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Organization");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Engagement", b =>
            {
                b.HasOne("StrikeShield.Domain.Entities.Project", "Project")
                    .WithMany("Engagements")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.PlaybookStep", b =>
            {
                b.HasOne("StrikeShield.Domain.Entities.Playbook", "Playbook")
                    .WithMany("Steps")
                    .HasForeignKey("PlaybookId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Playbook");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Project", b =>
            {
                b.HasOne("StrikeShield.Domain.Entities.Client", "Client")
                    .WithMany("Projects")
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Client");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.ScanJob", b =>
            {
                b.HasOne("StrikeShield.Domain.Entities.Engagement", "Engagement")
                    .WithMany("ScanJobs")
                    .HasForeignKey("EngagementId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("StrikeShield.Domain.Entities.Playbook", "Playbook")
                    .WithMany("ScanJobs")
                    .HasForeignKey("PlaybookId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("StrikeShield.Domain.Entities.Target", "Target")
                    .WithMany("ScanJobs")
                    .HasForeignKey("TargetId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Engagement");
                b.Navigation("Playbook");
                b.Navigation("Target");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.StepRun", b =>
            {
                b.HasOne("StrikeShield.Domain.Entities.PlaybookStep", "PlaybookStep")
                    .WithMany("StepRuns")
                    .HasForeignKey("PlaybookStepId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("StrikeShield.Domain.Entities.ScanJob", "ScanJob")
                    .WithMany("StepRuns")
                    .HasForeignKey("ScanJobId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("PlaybookStep");
                b.Navigation("ScanJob");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Target", b =>
            {
                b.HasOne("StrikeShield.Domain.Entities.Project", "Project")
                    .WithMany("Targets")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Client", b =>
            {
                b.Navigation("Projects");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Engagement", b =>
            {
                b.Navigation("ScanJobs");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Organization", b =>
            {
                b.Navigation("Clients");
                b.Navigation("Users");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Playbook", b =>
            {
                b.Navigation("ScanJobs");
                b.Navigation("Steps");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.PlaybookStep", b =>
            {
                b.Navigation("StepRuns");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Project", b =>
            {
                b.Navigation("Engagements");
                b.Navigation("Targets");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.ScanJob", b =>
            {
                b.Navigation("StepRuns");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.StepRun", b =>
            {
                b.Navigation("Artifacts");
            });

            modelBuilder.Entity("StrikeShield.Domain.Entities.Target", b =>
            {
                b.Navigation("ScanJobs");
            });
#pragma warning restore 612, 618
        }
    }
}
